apiVersion: v1
kind: Service
metadata:
  name: chatbot-processing
  namespace: ingress-basic
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: chatbot-processing