apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-processing
  template:
    metadata:
      labels:
        app: chatbot-processing
    spec:
      containers:
        - image: jurebevc/chatbot-processing:1.0.0-6.1
          name: chatbot-processing
          env:
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: db-path
                  key: db-path
            - name: REMOTE_CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: remote-config-path
                  key: remote-config-path
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8083
            periodSeconds: 3