version: "2"

networks:
  default:
    external:
      name: chatbot

services:
  chatbot-service:
    image: jurebevc/chatbot-processing
    container_name: chatbot-processing
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8083:8083
    environment:
      - DB_PATH=mysql+pymysql://root:123@db:3306/chatbot 
      #- DB_PATH=mysql+pymysql://sql7377269:MutA4e46L1@sql7.freemysqlhosting.net:3306/sql7377269