version: "2"

networks:
  default:
    external:
      name: chatbot

services:
  chatbot-service:
    image: jurebevc/chatbot-processing
    container_name: chatbot-processing
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8083:8083